### PR TITLE
Update config.def.h

### PR DESCRIPTION
**Pull request by DmitryHetman**
Changed default font and fontsize to Terminus 16px

### CODE REVIEW

**Comment by michaelforney** [comment]
No. Edit your local `config.h`.

**Comment by DmitryHetman** [comment]
Change size at least, 12 by default is horrible.

**Comment by michaelforney** [comment]
If you really want to change the default, send a patch to `hackers@suckless.org`. This st repository is just a branch of the official x11 st, and I won't be deviating from upstream just because you don't like the default.

**Comment by DmitryHetman** [comment]
Thanks

**Pull request closed without merging**
